# Generated by Django 5.1 on 2024-08-10 08:07

import base.models.base
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', base.models.base.ULIDField(default=ulid.api.api.Api.new, editable=False, help_text='Unique identifier for the {object_name}.', max_length=26, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the {object_name} is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the {object_name} was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the {object_name} was last updated.', null=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='The official name of the country.', max_length=100, unique=True, verbose_name='Country Name')),
                ('alpha2_code', models.CharField(help_text="The ISO 3166-1 alpha-2 code (e.g., 'US' for United States).", max_length=2, unique=True, verbose_name='Alpha-2 Code')),
                ('alpha3_code', models.CharField(help_text="The ISO 3166-1 alpha-3 code (e.g., 'USA' for United States).", max_length=3, unique=True, verbose_name='Alpha-3 Code')),
                ('numeric_code', models.CharField(help_text="The ISO 3166-1 numeric code (e.g., '840' for United States).", max_length=3, unique=True, verbose_name='Numeric Code')),
                ('isd_code', models.CharField(help_text="The International Subscriber Dialing code (e.g., '1' for the United States, '91' for India).", max_length=5, unique=True, verbose_name='ISD Code')),
                ('currency_name', models.CharField(blank=True, help_text='The name of the currency used in the country.', max_length=100, null=True, verbose_name='Currency Name')),
                ('currency_alpha3', models.CharField(blank=True, help_text="The ISO 4217 alpha-3 code for the currency (e.g., 'USD' for US Dollar).", max_length=3, null=True, verbose_name='Currency Alpha-3 Code')),
                ('currency_numeric_code', models.CharField(blank=True, help_text="The ISO 4217 numeric code for the currency (e.g., '840' for USD).", max_length=3, null=True, verbose_name='Currency Numeric Code')),
                ('currency_symbol', models.CharField(blank=True, help_text="The symbol used to represent the currency (e.g., '$', '€').", max_length=10, null=True, verbose_name='Currency Symbol')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', base.models.base.ULIDField(default=ulid.api.api.Api.new, editable=False, help_text='Unique identifier for the {object_name}.', max_length=26, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the {object_name} is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the {object_name} was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the {object_name} was last updated.', null=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='The official name of the state or province.', max_length=100, verbose_name='State Name')),
                ('code', models.CharField(blank=True, help_text="The code or abbreviation used for the state or province (e.g., 'CA' for California).", max_length=10, null=True, verbose_name='State Code')),
                ('country', models.ForeignKey(help_text='The country to which this state or province belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='base.modelcountry', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
                'ordering': ['name'],
            },
        ),
    ]
